apiVersion: v1
kind: ReplicationController     
metadata:
  name: autocomplete-frontend
  labels:
      app: autocomplete-frontend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: autocomplete-frontend
    spec:
      containers:
      - name: autocomplete-frontend
        image: gcr.io/gcp-autocomplete-davelindon-05/autocomplete:latest
        ports:
        - containerPort: 5000
          name: webui
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 5000
          initialDelaySeconds: 30
          timeoutSeconds: 30
