apiVersion: v1
kind: Service
metadata:
  name: autocomplete-app
  labels:
    app: autocomplete-app
spec:
  type: LoadBalancer
  selector:
    component: autocomplete-app
  ports:
  - name: http
    port: 80
    protocol: TCP