apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: autocomplete-frontend-as
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: ReplicationController
    name: autocomplete-frontend
  minReplicas: 6
  maxReplicas: 15
  targetCPUUtilizationPercentage: 50