apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: autocomplete-frontend-as
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: autocomplete-frontend
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50