apiVersion: v1
kind: Service
metadata:
  name: autocomplete-frontend
  labels:
    app: autocomplete-frontend
spec:
  selector:
    app: autocomplete-frontend
  ports:
  - port: 5000
    protocol: TCP
    targetPort: webui