apiVersion: v1
kind: ReplicationController     
metadata:
  name: autocomplete-backend
  labels:
      app: autocomplete-backend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: autocomplete-backend
    spec:
      containers:
      - name: autocomplete-backend
        image: gcr.io/gcp-autocomplete-davelindon-05/autocomplete:latest
        ports:
        - containerPort: 5000
          name: webui
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 5000
          initialDelaySeconds: 5
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 1
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 10
