apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: autocomplete-frontend
  annotations:
    kubernetes.io/ingress.global-static-ip-name: gcp-autocomplete-davelindon-global-ip
  labels:
    app: autocomplete-frontend
spec:
  backend:
    serviceName: autocomplete-backend
    servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: autocomplete-backend
  labels:
    app: autocomplete-backend
spec:
  type: NodePort
  selector:
    app: autocomplete-backend
  ports:
  - port: 80
    targetPort: 5000