apiVersion: batch/v1
kind: Job
metadata:
  name: dataloader-job
spec:
  template:
    spec:
      containers:
      - name: bestbuy-dataloader
        image: gcr.io/gcp-autocomplete-davelindon-05/dataloader:latest
      restartPolicy: OnFailure